- name: Create a GCP instance
  hosts: localhost
  vars:
     gcp_project: e_e
     gcp_cred_kind: serviceaccount
  tasks:
    - name: create a disk mapped from centos8 image
      gcp_compute_disk:
        name: "disk-instance-{{ 999 | random | to_uuid }}"
        size_gb: 20
        source_image: projects/centos-cloud/global/images/centos-8-v20201112
        zone: us-west1-b
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: disk

    - name: create a  VPC network
      gcp_compute_network:
        name: default
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: network

    - name: create an IPv4 public IP Address
      gcp_compute_address:
        name: "address-instance-{{ 999 | random | to_uuid }}"
        region: us-west1
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: address

    - name: create the centos8 instance
      gcp_compute_instance:
        name: "centos8-{{ 999 | random | to_uuid }}"
        machine_type: n1-standard-1
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        zone: us-west1-b
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
    - name: Show centos8 Instance Details
      debug:
        msg: "The centos8 instance is accessible at {{ address.address }}"
